'use client';
export const dynamic = 'force-dynamic';

/**
 * src/app/onboard/page.tsx
 *
 * Public tenant self-onboarding page.
 * URL: /onboard?token=XXX   (generated by /api/rental/invite-link/:unitId)
 *   or /onboard?ref=landlord (generic landlord invite — ask for token)
 *
 * Flow:
 *   1. Page loads → reads ?token from URL → GET /api/rental/onboard/preview/:token
 *      → shows property details & digital lease summary
 *   2. Tenant fills: full name, phone, email, password, guarantor (optional)
 *   3. POST /api/rental/onboard  → creates account + tenancy + vault
 *   4. Redirect to /tenant/dashboard
 *
 * If no token is present (/onboard?ref=landlord generic link):
 *   → Step 0: Ask tenant to paste their invite token or landlord email
 */

import { useState, useEffect } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import api from '@/lib/api';
import {
  Home, Shield, CheckCircle2, Loader2, AlertCircle,
  User, Mail, Phone, Lock, ArrowRight, Building2,
  Wallet, FileText, MessageCircle, Eye, EyeOff,
} from 'lucide-react';

// ── Helpers ───────────────────────────────────────────────────────────────────
const safeN = (v: any): number => { const n = Number(v); return (v == null || isNaN(n)) ? 0 : n; };
const safeF = (v: any): string => safeN(v).toLocaleString();

interface Preview {
  unit_name: string; property_name: string; location: string;
  monthly_rent: number; landlord_name: string; lease_start: string;
  flex_pay_available: boolean; token_expires: string;
}

type Step = 'token' | 'preview' | 'register' | 'success';

export default function TenantOnboardPage() {
  const searchParams = useSearchParams();
  const router       = useRouter();

  const urlToken = searchParams.get('token') ?? '';
  const ref      = searchParams.get('ref')   ?? '';

  const [step,     setStep]     = useState<Step>(urlToken ? 'preview' : 'token');
  const [token,    setToken]    = useState(urlToken);
  const [preview,  setPreview]  = useState<Preview | null>(null);
  const [loading,  setLoading]  = useState(!!urlToken);
  const [error,    setError]    = useState('');

  // ── Register form state ────────────────────────────────────────────────────
  const [form, setForm] = useState({
    full_name: '', email: '', phone: '', password: '', confirm_password: '',
    guarantor_name: '', guarantor_phone: '', frequency: 'MONTHLY',
  });
  const [showPass,   setShowPass]   = useState(false);
  const [submitting, setSubmitting] = useState(false);

  // ── Load preview when token is known ──────────────────────────────────────
  useEffect(() => {
    if (!token) return;
    setLoading(true); setError('');
    api.get(`/api/rental/onboard/preview/${token}`)
      .then(res => { setPreview(res.data.preview); setStep('preview'); })
      .catch(e => {
        setError(e?.response?.data?.error ?? 'Invalid or expired invite link.');
        setStep('token');
      })
      .finally(() => setLoading(false));
  }, [token]);

  // ── Submit registration ────────────────────────────────────────────────────
  const submit = async () => {
    if (!form.full_name || !form.email || !form.phone || !form.password) {
      setError('Please fill in all required fields.'); return;
    }
    if (form.password !== form.confirm_password) {
      setError('Passwords do not match.'); return;
    }
    if (form.password.length < 8) {
      setError('Password must be at least 8 characters.'); return;
    }
    setSubmitting(true); setError('');
    try {
      const res = await api.post('/api/rental/onboard', {
        token,
        full_name:       form.full_name,
        email:           form.email.toLowerCase(),
        phone:           form.phone,
        password:        form.password,
        guarantor_name:  form.guarantor_name || undefined,
        guarantor_phone: form.guarantor_phone || undefined,
        frequency:       form.frequency,
      });
      // Store auth token
      if (res.data.tokens?.access_token) {
        localStorage.setItem('token', res.data.tokens.access_token);
      }
      setStep('success');
      setTimeout(() => router.push('/tenant/dashboard'), 3000);
    } catch (e: any) {
      setError(e?.response?.data?.error ?? 'Registration failed — please try again.');
    } finally { setSubmitting(false); }
  };

  const set = (k: string) => (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) =>
    setForm(f => ({ ...f, [k]: e.target.value }));

  // ── Loading spinner ────────────────────────────────────────────────────────
  if (loading) return (
    <div className="min-h-screen bg-[#050505] text-white flex items-center justify-center">
      <div className="text-center space-y-4">
        <Loader2 className="animate-spin text-teal-500 mx-auto" size={32} />
        <p className="text-zinc-500 text-sm">Loading your invite…</p>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-[#050505] text-white">
      {/* Minimal header */}
      <header className="border-b border-zinc-900 px-6 py-4 flex items-center justify-between">
        <Link href="/" className="flex items-center gap-2.5">
          <div className="w-7 h-7 bg-teal-500 rounded-lg flex items-center justify-center">
            <Home size={14} className="text-black" />
          </div>
          <span className="font-black text-sm uppercase tracking-tighter">Nested Ark <span className="text-teal-500">OS</span></span>
        </Link>
        <span className="text-[9px] text-zinc-600 uppercase font-bold tracking-widest">Tenant Onboarding</span>
      </header>

      <main className="max-w-lg mx-auto px-6 py-12 space-y-8">

        {/* ── STEP: Token entry (generic invite link) ── */}
        {step === 'token' && (
          <div className="space-y-6">
            <div className="text-center space-y-3">
              <div className="w-16 h-16 bg-teal-500/10 border border-teal-500/30 rounded-3xl flex items-center justify-center mx-auto">
                <MessageCircle size={28} className="text-teal-400" />
              </div>
              <h1 className="text-3xl font-black uppercase tracking-tighter">Welcome</h1>
              <p className="text-zinc-400 text-sm leading-relaxed">
                Your landlord has invited you to manage your tenancy on Nested Ark.
                Enter your unique invite token below to get started.
              </p>
            </div>

            {error && (
              <div className="p-4 rounded-xl bg-red-500/5 border border-red-500/20 text-red-400 flex items-center gap-2 text-sm">
                <AlertCircle size={14} className="flex-shrink-0" /> {error}
              </div>
            )}

            <div className="space-y-3">
              <label className="text-[9px] text-zinc-500 uppercase font-bold tracking-widest block">Invite Token</label>
              <input value={token} onChange={e => setToken(e.target.value.trim())}
                placeholder="Paste your invite token here…"
                className="w-full bg-zinc-900 border border-zinc-700 rounded-xl px-4 py-4 text-sm text-white font-mono placeholder:text-zinc-700 focus:border-teal-500 outline-none" />
              <button onClick={() => { if (token) setStep('preview'); }}
                disabled={!token}
                className="w-full py-4 bg-teal-500 text-black font-black text-xs uppercase tracking-[0.2em] rounded-2xl hover:bg-teal-400 transition-all disabled:opacity-50 flex items-center justify-center gap-2">
                Continue <ArrowRight size={14} />
              </button>
            </div>

            <div className="text-center">
              <p className="text-[10px] text-zinc-600">Already have an account?{' '}
                <Link href="/login" className="text-teal-500 font-bold hover:text-white transition-colors">Sign in →</Link>
              </p>
            </div>

            {/* Trust indicators */}
            <div className="flex flex-wrap justify-center gap-4 pt-4 border-t border-zinc-900">
              {['SHA-256 Encrypted', 'Paystack Secured', 'Digital Lease', 'Flex-Pay Vault'].map(t => (
                <span key={t} className="flex items-center gap-1.5 text-[9px] text-zinc-700">
                  <Shield size={9} className="text-teal-500/50" /> {t}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* ── STEP: Preview property details ── */}
        {step === 'preview' && preview && (
          <div className="space-y-6">
            <div className="text-center space-y-2">
              <p className="text-[9px] text-teal-500 uppercase font-black tracking-[0.25em]">Your Invitation</p>
              <h1 className="text-3xl font-black uppercase tracking-tighter">Review & Accept</h1>
              <p className="text-zinc-500 text-sm">Confirm the details below, then set up your account and Flex-Pay vault.</p>
            </div>

            {/* Property card */}
            <div className="p-6 rounded-3xl border border-teal-500/20 bg-teal-500/5 space-y-5">
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 rounded-2xl bg-teal-500/20 border border-teal-500/30 flex items-center justify-center flex-shrink-0">
                  <Building2 size={22} className="text-teal-400" />
                </div>
                <div>
                  <p className="font-black text-lg uppercase tracking-tight">{preview.unit_name}</p>
                  <p className="text-zinc-400 text-sm">{preview.property_name}</p>
                  <p className="text-[10px] text-zinc-600 mt-1">{preview.location}</p>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                {[
                  { label: 'Monthly Rent',    value: `₦${safeF(preview.monthly_rent)}`,   color: 'text-teal-400' },
                  { label: 'Landlord',        value: preview.landlord_name,                color: 'text-white' },
                  { label: 'Lease Start',     value: preview.lease_start,                  color: 'text-white' },
                  { label: 'Flex-Pay',        value: preview.flex_pay_available ? '✓ Available' : 'Not available', color: preview.flex_pay_available ? 'text-teal-400' : 'text-zinc-500' },
                ].map(s => (
                  <div key={s.label} className="p-3 bg-zinc-900/60 rounded-xl border border-zinc-800">
                    <p className="text-[8px] text-zinc-600 uppercase font-bold mb-1">{s.label}</p>
                    <p className={`font-bold text-sm font-mono ${s.color}`}>{s.value}</p>
                  </div>
                ))}
              </div>

              {/* What you get */}
              <div className="pt-4 border-t border-zinc-800 space-y-2">
                <p className="text-[9px] text-zinc-500 uppercase font-bold tracking-widest">What you get</p>
                {[
                  'Digital tenancy agreement — SHA-256 signed',
                  'Flex-Pay Vault — pay weekly, monthly or quarterly',
                  'Auto receipts emailed on every payment',
                  'Legal transparency — all notices go through official channels',
                ].map(b => (
                  <div key={b} className="flex items-start gap-2 text-[10px] text-zinc-400">
                    <CheckCircle2 size={10} className="text-teal-500 flex-shrink-0 mt-0.5" /> {b}
                  </div>
                ))}
              </div>
            </div>

            <button onClick={() => setStep('register')}
              className="w-full py-4 bg-teal-500 text-black font-black text-xs uppercase tracking-[0.2em] rounded-2xl hover:bg-teal-400 transition-all flex items-center justify-center gap-2">
              Accept & Create My Account <ArrowRight size={14} />
            </button>
            <p className="text-center text-[9px] text-zinc-700">
              Token expires: {preview.token_expires ? new Date(preview.token_expires).toLocaleDateString() : 'N/A'}
            </p>
          </div>
        )}

        {/* ── STEP: Registration form ── */}
        {step === 'register' && (
          <div className="space-y-6">
            <div>
              <p className="text-[9px] text-teal-500 uppercase font-black tracking-[0.25em] mb-1">Step 2 of 2</p>
              <h1 className="text-2xl font-black uppercase tracking-tighter">Create Your Account</h1>
              <p className="text-zinc-500 text-xs mt-1">Your details are encrypted and never shared with third parties.</p>
            </div>

            {error && (
              <div className="p-4 rounded-xl bg-red-500/5 border border-red-500/20 text-red-400 flex items-center gap-2 text-sm">
                <AlertCircle size={14} className="flex-shrink-0" /> {error}
              </div>
            )}

            {/* Personal details */}
            <div className="space-y-3">
              <p className="text-[9px] text-zinc-500 uppercase font-bold tracking-widest">Personal Details</p>
              {[
                { key: 'full_name', label: 'Full Legal Name *', icon: User,  type: 'text',  placeholder: 'As on your ID document' },
                { key: 'email',     label: 'Email Address *',   icon: Mail,  type: 'email', placeholder: 'you@email.com' },
                { key: 'phone',     label: 'Phone Number *',    icon: Phone, type: 'tel',   placeholder: '+234 800 000 0000' },
              ].map(f => {
                const Icon = f.icon;
                return (
                  <div key={f.key} className="relative">
                    <Icon size={13} className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-600" />
                    <input type={f.type} value={(form as any)[f.key]} onChange={set(f.key)}
                      placeholder={f.placeholder}
                      className="w-full bg-zinc-900 border border-zinc-700 rounded-xl pl-10 pr-4 py-3.5 text-sm text-white placeholder:text-zinc-700 focus:border-teal-500 outline-none" />
                  </div>
                );
              })}
            </div>

            {/* Password */}
            <div className="space-y-3">
              <p className="text-[9px] text-zinc-500 uppercase font-bold tracking-widest">Set Password</p>
              <div className="relative">
                <Lock size={13} className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-600" />
                <input type={showPass ? 'text' : 'password'} value={form.password} onChange={set('password')}
                  placeholder="Min. 8 characters"
                  className="w-full bg-zinc-900 border border-zinc-700 rounded-xl pl-10 pr-12 py-3.5 text-sm text-white placeholder:text-zinc-700 focus:border-teal-500 outline-none" />
                <button type="button" onClick={() => setShowPass(v => !v)}
                  className="absolute right-4 top-1/2 -translate-y-1/2 text-zinc-600 hover:text-white transition-colors">
                  {showPass ? <EyeOff size={14} /> : <Eye size={14} />}
                </button>
              </div>
              <div className="relative">
                <Lock size={13} className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-600" />
                <input type={showPass ? 'text' : 'password'} value={form.confirm_password} onChange={set('confirm_password')}
                  placeholder="Confirm password"
                  className="w-full bg-zinc-900 border border-zinc-700 rounded-xl pl-10 pr-4 py-3.5 text-sm text-white placeholder:text-zinc-700 focus:border-teal-500 outline-none" />
              </div>
            </div>

            {/* Flex-Pay frequency */}
            <div className="space-y-2">
              <p className="text-[9px] text-zinc-500 uppercase font-bold tracking-widest">Preferred Payment Schedule</p>
              <div className="grid grid-cols-3 gap-2">
                {[
                  { key: 'WEEKLY',    label: 'Weekly',    sub: 'Every week' },
                  { key: 'MONTHLY',   label: 'Monthly',   sub: 'Once a month' },
                  { key: 'QUARTERLY', label: 'Quarterly', sub: 'Every 3 months' },
                ].map(f => (
                  <button key={f.key} type="button" onClick={() => setForm(p => ({...p, frequency: f.key}))}
                    className={`p-3 rounded-xl border text-left transition-all ${form.frequency === f.key ? 'border-teal-500 bg-teal-500/10' : 'border-zinc-800 bg-zinc-900/20 hover:border-zinc-700'}`}>
                    <p className="text-[10px] font-black uppercase">{f.label}</p>
                    <p className="text-[8px] text-zinc-500 mt-0.5">{f.sub}</p>
                    {form.frequency === f.key && <CheckCircle2 size={10} className="text-teal-400 mt-1" />}
                  </button>
                ))}
              </div>
            </div>

            {/* Guarantor (optional) */}
            <div className="space-y-3">
              <p className="text-[9px] text-zinc-500 uppercase font-bold tracking-widest">Guarantor Details <span className="text-zinc-700 normal-case font-normal">(optional)</span></p>
              <div className="relative">
                <User size={13} className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-600" />
                <input type="text" value={form.guarantor_name} onChange={set('guarantor_name')}
                  placeholder="Guarantor's full name"
                  className="w-full bg-zinc-900 border border-zinc-700 rounded-xl pl-10 pr-4 py-3.5 text-sm text-white placeholder:text-zinc-700 focus:border-teal-500 outline-none" />
              </div>
              <div className="relative">
                <Phone size={13} className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-600" />
                <input type="tel" value={form.guarantor_phone} onChange={set('guarantor_phone')}
                  placeholder="Guarantor's phone number"
                  className="w-full bg-zinc-900 border border-zinc-700 rounded-xl pl-10 pr-4 py-3.5 text-sm text-white placeholder:text-zinc-700 focus:border-teal-500 outline-none" />
              </div>
            </div>

            {/* Digital lease consent */}
            <div className="p-4 rounded-2xl border border-zinc-800 bg-zinc-900/20 flex items-start gap-3">
              <FileText size={16} className="text-teal-500 flex-shrink-0 mt-0.5" />
              <p className="text-[10px] text-zinc-500 leading-relaxed">
                By creating an account, you agree to the digital tenancy agreement for <strong className="text-white">{preview?.unit_name}</strong>.
                Your tenancy will be SHA-256 hashed and recorded on the Nested Ark immutable ledger.
                Your Flex-Pay vault will be activated automatically on registration.
              </p>
            </div>

            <button onClick={submit} disabled={submitting}
              className="w-full py-4 bg-teal-500 text-black font-black text-xs uppercase tracking-[0.2em] rounded-2xl hover:bg-teal-400 transition-all disabled:opacity-60 flex items-center justify-center gap-2">
              {submitting ? <Loader2 size={14} className="animate-spin" /> : <Wallet size={14} />}
              {submitting ? 'Creating your account…' : 'Activate My Tenancy & Vault'}
            </button>

            <p className="text-center text-[9px] text-zinc-700">
              Already have an account?{' '}
              <Link href="/login" className="text-teal-500 font-bold hover:text-white transition-colors">Sign in →</Link>
            </p>
          </div>
        )}

        {/* ── STEP: Success ── */}
        {step === 'success' && (
          <div className="text-center space-y-6 py-10">
            <div className="w-20 h-20 bg-teal-500/10 border border-teal-500/30 rounded-full flex items-center justify-center mx-auto">
              <CheckCircle2 size={40} className="text-teal-400" />
            </div>
            <div className="space-y-2">
              <h2 className="text-3xl font-black uppercase tracking-tighter text-teal-400">You're In!</h2>
              <p className="text-zinc-400 text-sm leading-relaxed">
                Your tenancy has been activated and your Flex-Pay vault is ready.
                You'll receive a confirmation email with your digital lease.
              </p>
            </div>
            <div className="flex flex-wrap justify-center gap-3 pt-4">
              {['Tenancy Activated', 'Vault Ready', 'Lease Signed', 'Email Sent'].map(b => (
                <span key={b} className="flex items-center gap-1.5 text-[9px] text-teal-400 font-bold uppercase tracking-wider px-3 py-1.5 rounded-full border border-teal-500/20 bg-teal-500/5">
                  <CheckCircle2 size={9} /> {b}
                </span>
              ))}
            </div>
            <p className="text-[10px] text-zinc-600">Redirecting to your dashboard in 3 seconds…</p>
            <Link href="/tenant/dashboard"
              className="inline-flex items-center gap-2 px-6 py-3 bg-teal-500 text-black font-black text-xs uppercase tracking-widest rounded-xl hover:bg-teal-400 transition-all">
              Go to Dashboard <ArrowRight size={12} />
            </Link>
          </div>
        )}

      </main>
    </div>
  );
}
